theme = "dark_plus_nobg"

[editor]
line-number = "relative"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

# [keys.normal]
# ";"  = "command_mode"

[editor.statusline]
mode.normal = "  ---  N O R M A L  ---  "
mode.insert = "  ---  I N S E R T  ---  "
mode.select = "  ---  S E L E C T  ---  "
