theme = "dark_plus_nobg"

[editor]
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

# [keys.normal]
# ";"  = "command_mode"

[editor.statusline]
mode.normal = " -- NORMAL -- "
mode.insert = " -- INSERT -- "
mode.select = " -- SELECT -- "
