[mgr]
prepend_keymap = [
    { on = "/",             run = "filter --smart",         desc = "Filter files" },
    { on = "!",             run = 'shell "tmux -L tmux-yazi" --block', desc = "Open shell here" },
    { on = "<Home>",        run = "arrow top",              desc = "Move cursor to the top" },
    { on = "<End>",         run = "arrow bot",              desc = "Move cursor to the bottom" },
    { on = "<Delete>",      run = "remove",                 desc = "Trash selected files" },
    { on = "<S-Delete>",    run = "remove --permanently",   desc = "Permanently delete selected files" },

#    { on = "<S-PageUp>",    run = "seek -20",               desc = "Seek up 20 units in the preview" },
#    { on = "<S-PageDown>",  run = "seek 20",                desc = "Seek down 20 units in the preview" },
#    { on = "<S-Up>",        run = "seek -5",                desc = "Seek up 5 units in the preview" },
#    { on = "<S-Down>",      run = "seek 5",                 desc = "Seek down 5 units in the preview" },

    { on = "<Esc>",         run = "plugin smart-nav escape",        desc = "Smart Navigation" },
    { on = "<Backspace>",   run = "plugin smart-nav leave",         desc = "Smart Navigation" },
    { on = "<Left>",        run = "plugin smart-nav leave",         desc = "Smart Navigation" },
    { on = "<Right>",       run = "plugin smart-nav enter",         desc = "Smart Navigation" },
    { on = "<Enter>",       run = "plugin smart-nav enter",         desc = "Smart Navigation" },
    { on = "<Up>",          run = "plugin smart-nav -- arrow prev", desc = "Smart Navigation" },
    { on = "<Down>",        run = "plugin smart-nav -- arrow next", desc = "Smart Navigation" },
    { on = "<S-Up>",        run = "plugin smart-nav -- arrow -5",   desc = "Smart Navigation" },
    { on = "<S-Down>",      run = "plugin smart-nav -- arrow  5",   desc = "Smart Navigation" },

    { on = [ "c", "D" ],        run = "copy dirname",       desc = "Copy the directory path" },
    { on = [ "c", "d" ],        run = "cd --interactive",   desc = "Change directory" },
    { on = [ "<Space>", "g" ],  run = "cd --interactive",   desc = "Change directory" },
    { on = [ "<Space>", "f" ],  run = "search --via=fd",    desc = "Search file name via fd" },
    { on = [ "<Space>", "/" ],  run = "search --via=rg",    desc = "Search file content via ripgrep" },
    { on = [ "<Space>", "r" ],  run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" }

]

[tasks]
prepend_keymap = [
    { on = "<Delete>",  run = "cancel",     desc = "Cancel the task" },
    { on = "d",         run = "cancel",     desc = "Cancel the task" }
]

[input]
prepend_keymap = [
    { on = "<Esc>", run = "close",  desc = "Cancel input" }
]

[completion]
prepend_keymap = [
    { on = "<Esc>", run = "close",  desc = "Cancel completion" }
]

[help]
prepend_keymap = [
    { on = "/",     run = "filter", desc = "Apply a filter for the help items" }
]
