[manager]
prepend_keymap = [
    { on = "<Backspace>",   run = "leave",                  desc = "Go back to the parent directory" },
    { on = "<Enter>",       run = "enter",                  desc = "Enter the child directory" },
    { on = "/",             run = "filter --smart",         desc = "Filter files" },
    { on = "<Home>",        run = "arrow -9999999",         desc = "Move cursor to the top" },
    { on = "<End>",         run = "arrow 9999999",          desc = "Move cursor to the bottom" },
    { on = "<Delete>",      run = "remove",                 desc = "Trash selected files" },
    { on = "<S-Delete>",    run = "remove --permanently",   desc = "Permanently delete selected files" },

    { on = [ "c", "d" ],        run = "cd --interactive",   desc = "Jump interactive" },
    { on = [ "<Space>", "g" ],  run = "cd --interactive",   desc = "Jump interactive" },
    { on = [ "<Space>", "f" ],  run = "search --via=fd",    desc = "Search file name via fd" },
    { on = [ "<Space>", "/" ],  run = "search --via=rg",    desc = "Search file content via ripgrep" },
    { on = [ "<Space>", "r" ],  run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" }

]

[tasks]
prepend_keymap = [
    { on = "<Delete>",  run = "cancel",     desc = "Cancel the task" },
    { on = "d",         run = "cancel",     desc = "Cancel the task" }
]

[input]
prepend_keymap = [
    { on = "<Esc>", run = "close",  desc = "Cancel input" }
]

[completion]
prepend_keymap = [
    { on = "<Esc>", run = "close",  desc = "Cancel completion" }
]

[help]
prepend_keymap = [
    { on = "/",     run = "filter", desc = "Apply a filter for the help items" }
]