[mgr]
ratio          = [ 3, 7, 6 ]
show_hidden    = true

[preview]
image_delay     = 100
max_width       = 1800
max_height      = 1500
# image_filter    = "triangle"
# image_filter    = "catmull-rom"
# image_filter    = "lanczos3"

[plugin]
preloaders = []

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"